---
$schema: 'http://json-schema.org/draft-04/schema#'
definitions:
  auth:
    description: The auth token
    type: string
    example: eb25f25becca416092752b0f457f1271
  note_id:
    description: Auto-increment ID.
    type: integer
    example: 1
  body:
    description: Text body of the note.
    type: string
    example: This is an example note.
  done:
    description: Indicates whether the task is complete.
    type: boolean
    example: true
  limit:
    description: The maximum number of notes to retrieve.
    type:
      - integer
      - 'null'
    example: 10
  note:
    $ref: '#'
  notes:
    description: An array of note objects.
    example:
    - note_id: 1
      body: This is an example note.
      done: true
    - note_id: 2
      body: This is another example note.
      done: false
    type: array
    items:
      $ref: '#'
  offset:
    description: The offset to use when fetching a subset of notes.
    type: integer
    example: 0
example:
  description: A note object.
  example:
    note_id: 1
    body: This is an example note.
    done: true
type: object
properties:
  note_id:
    $ref: '#/definitions/note_id'
  body:
    $ref: '#/definitions/body'
  done:
    $ref: '#/definitions/done'
additionalProperties: no
required:
  - note_id
  - body
